routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventController;
use App\Http\Controllers\ParentsController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ConfidantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::resource('students', StudentController::class);

    Route::resource('parents', ParentsController::class);

    Route::resource('confidants', ConfidantController::class);

    Route::resource('events', EventController::class);

    Route::get('/students/{student}/parents', [StudentController::class, 'parents'])->name('students.parents');

    Route::get('/events/{event}/logs', [EventController::class, 'logs'])->name('events.logs');
});

require __DIR__.'/auth.php';

app/Models/Student.php
<?php

namespace App\Models;

use App\Traits\Statusable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Student extends Model
{
    use HasFactory, Statusable;

    /**
     * @inheritdoc
     */
    protected $fillable = [
        'first_name', 'last_name', 'middle_name', 'phone', 'telegram', 'birthday', 'status'
    ];

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * Get the comments for the blog post.
     */
    public function parents()
    {
        return $this->hasMany(Parents::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Contracts\View\View;
use Illuminate\Contracts\View\Factory;
use App\Http\Requests\StoreStudentRequest;
use App\Http\Requests\UpdateStudentRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View|Factory
     */
    public function index()
    {
        return view('students.index', [
            'students' => Student::paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View|Factory
     */
    public function create()
    {
        return view('students.create',[
            'student' => new Student()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreStudentRequest $request
     * @return RedirectResponse
     */
    public function store(StoreStudentRequest $request)
    {
        Student::create($request->validated());

        return redirect()->route('students.index')->with('success', 'Ученик Добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param Student $student
     * @return View|Factory
     */
    public function show(Student $student)
    {
        return view('students.show', [
            'student' => $student
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Student $student
     * @return View|Factory
     */
    public function edit(Student $student)
    {
        return view('students.edit', [
            'student' => $student
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateStudentRequest $request
     * @param Student              $student
     * @return RedirectResponse
     */
    public function update(UpdateStudentRequest $request, Student $student)
    {
        $student->update($request->validated());

        return redirect()->route('students.index')->with('success', 'Ученик Обновлен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Student $student
     * @return JsonResponse
     */
    public function destroy(Student $student)
    {
        $student->delete();

        return response()->json(['status' => 'success', 'message' => 'Ученик Удален!']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return View|Factory
     */
    public function parents(Student $student)
    {
        return view('students.parents', [
            'student' => $student,
            'parents' => $student->parents()->paginate()
        ]);
    }
}

resources/views/students/create.blade.php
@extends('layouts.admin')

@section('title', 'Добавление Ученика')
@section('section', 'Управление Учениками')
@section('breadcrumbs', Breadcrumbs::render('students.create'))
@section('content')
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Добавление</strong> Ученика</h2>
        </header>

        {!! Form::open(['route' => 'students.store', 'class' => 'form body-tile']) !!}
        @include('students.form', ['student' => $student])
        {!! Form::close() !!}
    </section>
@stop

resources/views/students/edit.blade.php
@extends('layouts.admin')

@section('title', 'Редактирование Ученика')
@section('section', 'Управление Учениками')
@section('breadcrumbs', Breadcrumbs::render('students.edit', $student))
@section('content')
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Редактирование</strong> Пользователя</h2>
        </header>

        {!! Form::model($student, ['route' => ['students.update', $student->id], 'method' => 'PUT', 'class' => 'form body-tile']) !!}
        @include('students.form', ['student' => $student])
        {!! Form::close() !!}
    </section>
@stop

resources/views/students/form.blade.php
<div class="row">
    <div class="col form-item">
        {!! Form::label('last_name', 'Фамилия:') !!}
        {!! Form::text('last_name', null, ['class' => 'inp', 'placeholder' => 'Иванов', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('first_name', 'Имя:') !!}
        {!! Form::text('first_name', null, ['class' => 'inp', 'placeholder' => 'Иван', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('middle_name', 'Отчество:') !!}
        {!! Form::text('middle_name', null, ['class' => 'inp', 'placeholder' => 'Иванович']) !!}
    </div>
</div>

<div class="row">
    <div class="col form-item">
        {!! Form::label('telegram', 'Telegram:') !!}
        {!! Form::text('telegram', null, ['class' => 'inp', 'placeholder' => '@ivan', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('phone', 'Телефон:') !!}
        {!! Form::tel('phone', null, ['class' => 'inp', 'placeholder' => '79001234567', 'required']) !!}
    </div>
</div>

<div class="row">
    <div class="col form-item">
        {!! Form::label('birthday', 'Дата Рождения:') !!}
        {!! Form::date('birthday', null, ['class' => 'inp', 'placeholder' => '12.12.2010', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('status', 'Статус:') !!}
        {!! Form::select('status', $student->statusList(), null, ['class' => 'select', 'required']) !!}
    </div>
</div>

<footer class="row footer-tile">
    <a href="{{ URL::previous() }}" class="button light-red">Отмена</a>
    <input type="submit" value="Сохранить" class="button success">
</footer>

resources/views/students/index.blade.php
@extends('layouts.admin')

@section('title', 'Обзор Учеников')
@section('section', 'Управление Учениками')
@section('breadcrumbs', Breadcrumbs::render('students.index'))
@section('content')
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Обзор</strong> Учеников</h2>

            <nav class="controls">
                <a href="{!! route('students.create') !!}"><i class="fa fa-plus"></i> Добавить Ученика</a>
            </nav>
        </header>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Телефон</th>
                <th>Telegram</th>
                <th class="center">Статус</th>
                <th>Дата Регистрации</th>
                <th class="action-column">Действия</th>
            </tr>
            </thead>
            <tbody>
            @forelse($students as $student)
                <tr>
                    <td>{{ $student->id }}.</td>
                    <td>{{ $student->first_name }}</td>
                    <td>{{ $student->last_name }}</td>
                    <td>{{ $student->middle_name }}</td>
                    <td>{{ $student->phone }}</td>
                    <td>{{ $student->telegram }}</td>
                    <td class="center">{!! $student->status_icon !!}</td>
                    <td>@datetime($student->created_at)</td>
                    <td class="action-column">
                        <a href="{!! route('students.parents', [$student->id]) !!}" class="button with-icon"
                           data-tooltip="Родители"><i class="fa fa-user"></i></a>
                        <a href="{!! route('students.show', [$student->id]) !!}" class="button with-icon"
                           data-tooltip="Просмотр"><i class="fa fa-eye"></i></a>
                        <a href="{!! route('students.edit', [$student->id]) !!}" class="button with-icon"
                           data-tooltip="Изменить"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" class="button with-icon" data-tooltip="Удалить"
                           data-delete="{{ $student->id }}"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9">
                        <div class="message warning" role="alert">Ученики не найдены!</div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>

        {{ $students->links() }}
    </section>
@stop

resources/views/students/parents.blade.php
@extends('layouts.admin')

@section('title', 'Обзор Родителей')
@section('section', 'Управление Родителями')
@section('breadcrumbs', Breadcrumbs::render('students.parents', $student))
@section('content')
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Обзор</strong> Родителей</h2>

            <nav class="controls">
                <a href="{!! route('parents.create') !!}"><i class="fa fa-plus"></i> Добавить Родителя</a>
            </nav>
        </header>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Телефон</th>
                <th>Telegram</th>
                <th class="center">Статус</th>
                <th>Дата Регистрации</th>
                <th class="action-column">Действия</th>
            </tr>
            </thead>
            <tbody>
            @forelse($parents as $parent)
                <tr>
                    <td>{{ $parent->id }}.</td>
                    <td>{{ $parent->first_name }}</td>
                    <td>{{ $parent->last_name }}</td>
                    <td>{{ $parent->middle_name }}</td>
                    <td>{{ $parent->phone }}</td>
                    <td>{{ $parent->telegram }}</td>
                    <td class="center">{!! $parent->status_icon !!}</td>
                    <td>@datetime($parent->created_at)</td>
                    <td class="action-column">
                        <a href="{!! route('parents.show', [$parent->id]) !!}" class="button with-icon"
                           data-tooltip="Просмотр"><i class="fa fa-eye"></i></a>
                        <a href="{!! route('parents.edit', [$parent->id]) !!}" class="button with-icon"
                           data-tooltip="Изменить"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" class="button with-icon" data-tooltip="Удалить"
                           data-delete="{{ $parent->id }}"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9">
                        <div class="message warning" role="alert">Родители не найдены!</div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>

        {{ $parents->links() }}
    </section>
@stop

resources/views/students/show.blade.php
@extends('layouts.admin')

@section('title', 'Просмотр Ученика')
@section('section', 'Управление Учениками')
@section('breadcrumbs', Breadcrumbs::render('students.show', $student))
@section('content')
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Просмотр</strong> Ученика</h2>
        </header>

        <article class="body-tile form">
            <div class="row">
                <div class="col form-item">
                    <span class="label">Имя:</span>
                    <span class="inp">{{ $student->first_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Фамилия:</span>
                    <span class="inp">{{ $student->last_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Отчество:</span>
                    <span class="inp">{{ $student->middle_name }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Telegram:</span>
                    <span class="inp">{{ $student->telegram }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Телефон:</span>
                    <span class="inp">{{ $student->phone }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Дата Рождения:</span>
                    <span class="inp">@datetime($student->created_at)</span>
                </div>
                <div class="col form-item">
                    <span class="label">Статус:</span>
                    <span class="inp">{{ $student->status_text }}</span>
                </div>
            </div>

            <footer class="row footer-tile">
                <a href="{{ URL::previous() }}" class="button">Назад</a>
            </footer>
        </article>
    </section>
@stop